id: P65D46325
initial_creation_type: ocr
source_metadata:
  work_id: http://purl.bdrc.io/resource/WA1KG6198
  instance_id: http://purl.bdrc.io/resource/IE1KG6198
  collection_id: http://purl.bdrc.io/resource/PR0ET009
  language_id: http://purl.bdrc.io/resource/LangBo
  title:
    bo:
    - འཚུབ་མ་ཁེར་རྐྱང་།
  alt_title:
    zh-hans:
    - 寂寞旋风
  author: http://purl.bdrc.io/resource/P1KG6173
  publisher: UCB-OCR
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  volumes:
    bea0221a49bf4517924cab085a3592e7:
      title: པོད ༡་འཚུབ་མ་ཁེར་རྐྱང་།
      volume_number: 1
      base_file: UT1KG6198_I1KG6232_0000.txt
      reference: http://purl.bdrc.io/resource/VL79DCAE0D15EA0CBD
      image_group: I1KG6232
      quality: Low
  reproductionOf:
  - http://purl.bdrc.io/resource/W1KG6198
  - http://purl.bdrc.io/resource/MW1KG6198
  ocr_software: Namsel
created_at: '2021-12-22T10:57:49.025568'
last_modified_at: '2021-12-22T10:57:49.025575'
